### ISSUE TITLE
Does not work with Waymo Dataset

### ISSUE THREAD

**Issue by polleyr** [jongwook/tfrecord_lite#2]
Hi,

i want to inspect the [waymo dataset](https://waymo.com/open/data/). I downloaded the first tar file (training_0000.tar) and extracted the first tfrecord file which is called `segment-10241508783381919015_2889_360_2909_360_with_camera_labels.tfrecord`.

When I use your code do inspect this file I get the following error:

> terminate called after throwing an instance of 'std::runtime_error'
>   what():  Decoding failed: callback failed
> Aborted (core dumped)

My code is the following, I changed the path to the correct path:

```
from tfrecord_lite import tf_record_iterator

path = 'path/to/segment/segment-10241508783381919015_2889_360_2909_360_with_camera_labels.tfrecord'
it = tf_record_iterator(path)
next(it)

```

**Comment by jongwook** [comment]
Hi, upon some inspection, it turns out that Waymo is (ab)using the tfrecord format to encode their own [protocols](https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/dataset.proto) where each chunk contains `waymo_open_dataset.dataset_pb2.Frame` messages.

This library only supports TensorFlow's `tf.train.Example` messages, which contains `tf.train.Features`, and does not support arbitrary other protobuf message formats.

I'd suggest using [Waymo's toolset](https://github.com/waymo-research/waymo-open-dataset) for working with their dataset.
